[book]
authors = ["Anna"]
language = "en"
src = "src"
title = "Heliosphere Documentation"

[output.html]
preferred-dark-theme = "ayu"
cname = "docs.heliosphere.app"
git-repository-url = "https://github.com/heliosphere-xiv/docs"
edit-url-template = "https://github.com/heliosphere-xiv/docs/edit/main/{path}"
